apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring
spec:
  groups:
    - name: test.rules
      rules:
        - alert: TestAlert
          expr: vector(1)  # دايمًا true، يبقى alert يظهر فورًا
          for: 10s        # هيتأكد بعد 10 ثواني
          labels:
            severity: critical
          annotations:
            summary: "This is a test alert"
            description: "Alert to test Alertmanager configuration"

